import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
// Temporarily commented out for local development
// import { fetchAuthSession } from 'aws-amplify/auth';
// import axios from 'axios';
import '../styles/SchemeDetail.css';

interface SchemeData {
  scheme_id: string;
  scheme_name: string;
  ministry?: string;
  target_beneficiaries?: string[];
  benefits?: string[];
  eligibility_criteria?: any[];
  application_steps?: string[];
  documents_required?: string[];
  official_url?: string;
}

function SchemeDetail() {
  const { schemeId } = useParams();
  const navigate = useNavigate();
  const [scheme, setScheme] = useState<SchemeData | null>(null);
  const [explanation, setExplanation] = useState<string>('');
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);

  useEffect(() => {
    loadSchemeDetails();
  }, [schemeId]);

  const loadSchemeDetails = async () => {
    try {
      setIsLoading(true);

      // Temporarily simulate API call for local development
      await new Promise(resolve => setTimeout(resolve, 1500)); // Simulate API delay

      // Mock scheme data based on schemeId
      const mockSchemes: Record<string, SchemeData> = {
        'pm-kisan': {
          scheme_id: 'pm-kisan',
          scheme_name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
          ministry: 'Ministry of Agriculture & Farmers Welfare',
          target_beneficiaries: ['Small and marginal farmers', 'Land-owning farmers'],
          benefits: ['₹6,000 per year in three installments', 'Direct bank transfer', 'No processing fee'],
          eligibility_criteria: [
            'Must be a citizen of India',
            'Must own cultivable land',
            'Family income should not exceed ₹2 lakh per annum'
          ],
          application_steps: [
            'Visit the official PM-KISAN website',
            'Register with Aadhaar number',
            'Verify land records',
            'Submit application',
            'Wait for verification and approval'
          ],
          documents_required: [
            'Aadhaar Card',
            'Bank Account Details',
            'Land Records',
            'Mobile Number'
          ],
          official_url: 'https://pmkisan.gov.in/'
        },
        'ayushman-bharat': {
          scheme_id: 'ayushman-bharat',
          scheme_name: 'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PMJAY)',
          ministry: 'Ministry of Health & Family Welfare',
          target_beneficiaries: ['Economically weaker sections', 'Low-income families'],
          benefits: ['Up to ₹5 lakh per family per year', 'Cashless treatment', 'Coverage for 1,350+ procedures'],
          eligibility_criteria: [
            'Family income should not exceed ₹5 lakh per annum',
            'Must have a valid Ayushman Bharat card',
            'Priority given to rural and urban poor families'
          ],
          application_steps: [
            'Check eligibility on official website',
            'Apply through Common Service Centres (CSC)',
            'Get Ayushman Bharat card',
            'Visit empaneled hospital',
            'Get cashless treatment'
          ],
          documents_required: [
            'Aadhaar Card',
            'Income Certificate',
            'Ration Card',
            'Bank Account Details'
          ],
          official_url: 'https://pmjay.gov.in/'
        },
        'mudra-loan': {
          scheme_id: 'mudra-loan',
          scheme_name: 'Pradhan Mantri Mudra Yojana (PMMY)',
          ministry: 'Ministry of Finance',
          target_beneficiaries: ['Small entrepreneurs', 'Self-employed individuals', 'Small business owners'],
          benefits: ['Loans up to ₹10 lakh', 'No collateral required', 'Flexible repayment terms'],
          eligibility_criteria: [
            'Must be an Indian citizen',
            'Age between 18-65 years',
            'Should have a viable business plan'
          ],
          application_steps: [
            'Approach nearest bank or financial institution',
            'Submit business plan and documents',
            'Get loan approval',
            'Receive loan amount',
            'Start your business'
          ],
          documents_required: [
            'Aadhaar Card',
            'PAN Card',
            'Business Plan',
            'Bank Account Details',
            'Address Proof'
          ],
          official_url: 'https://www.mudra.org.in/'
        }
      };

      const schemeData = mockSchemes[schemeId || ''] || mockSchemes['pm-kisan'];
      setScheme(schemeData);

      // Mock explanation
      setExplanation(`This is a demo explanation for ${schemeData.scheme_name}. In the full application, this would be generated by AI based on your profile and the scheme details.`);

      // Mock audio URL (would be generated by voice API)
      setAudioUrl(null); // No audio in demo mode

    } catch (error) {
      console.error('Error loading scheme details:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const playAudio = () => {
    if (audioUrl) {
      const audio = new Audio(audioUrl);
      setIsPlayingAudio(true);
      audio.play();
      audio.onended = () => setIsPlayingAudio(false);
    }
  };

  if (isLoading) {
    return (
      <div className="scheme-detail-container">
        <div className="loading">
          <div className="spinner"></div>
          <p>Loading scheme details...</p>
        </div>
      </div>
    );
  }

  if (!scheme) {
    return (
      <div className="scheme-detail-container">
        <div className="error">
          <p>Scheme not found</p>
          <button onClick={() => navigate('/results')} className="btn-primary">
            Back to Results
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="scheme-detail-container">
      <header className="detail-header">
        <button onClick={() => navigate('/results')} className="btn-back">
          ← Back to Results
        </button>
      </header>

      <div className="scheme-content">
        <div className="scheme-title">
          <h1>{scheme.scheme_name}</h1>
          {scheme.ministry && <p className="ministry">{scheme.ministry}</p>}
        </div>

        <div className="explanation-section">
          <h2>Explanation</h2>
          <p className="explanation-text">{explanation}</p>
          
          {audioUrl && (
            <button
              className="btn-audio"
              onClick={playAudio}
              disabled={isPlayingAudio}
            >
              {isPlayingAudio ? '🔊 Playing...' : '🔊 Listen in Hindi'}
            </button>
          )}
        </div>

        {scheme.benefits && scheme.benefits.length > 0 && (
          <div className="section">
            <h2>Benefits</h2>
            <ul>
              {scheme.benefits.map((benefit, index) => (
                <li key={index}>{benefit}</li>
              ))}
            </ul>
          </div>
        )}

        {scheme.eligibility_criteria && scheme.eligibility_criteria.length > 0 && (
          <div className="section">
            <h2>Eligibility Criteria</h2>
            <ul>
              {scheme.eligibility_criteria.map((criteria, index) => (
                <li key={index}>
                  {criteria.field}: {criteria.operator} {criteria.value}
                </li>
              ))}
            </ul>
          </div>
        )}

        {scheme.documents_required && scheme.documents_required.length > 0 && (
          <div className="section">
            <h2>Required Documents</h2>
            <ul>
              {scheme.documents_required.map((doc, index) => (
                <li key={index}>{doc}</li>
              ))}
            </ul>
          </div>
        )}

        {scheme.application_steps && scheme.application_steps.length > 0 && (
          <div className="section">
            <h2>How to Apply</h2>
            <ol>
              {scheme.application_steps.map((step, index) => (
                <li key={index}>{step}</li>
              ))}
            </ol>
          </div>
        )}

        {scheme.official_url && (
          <div className="section">
            <a
              href={scheme.official_url}
              target="_blank"
              rel="noopener noreferrer"
              className="btn-primary"
            >
              Visit Official Website →
            </a>
          </div>
        )}
      </div>
    </div>
  );
}

export default SchemeDetail;
